# Site settings

title: Mandelbots
email: Jeff@pcjs.org
description: >
  Interactive JavaScript widgets that produce images of the Mandelbrot Set.  Designed to support
  any desktop or mobile web browser with either a mouse or touch interface.
baseurl: ""
domain: mandelbot.net
url: "https://mandelbot.net"
twitter_username: mandelbotnet
github_username:  jeffpar
google_analytics: UA-49658648-2

# Build settings

theme: jekyll-theme-cayman
exclude: ["CNAME", "debug.html", "Gemfile*", "modules", "node_modules", "package.json", "README.*"]
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
