# Site settings

title: "MandelBot"
email: Jeff@pcjs.org
description: >
  Welcome to MandelBot!
baseurl: ""
url: "http://mandelbot.net"
twitter_username: jeffpar
github_username:  jeffpar
google_analytics: UA-49658648-2

# Build settings

theme: jekyll-theme-cayman
exclude: ["CNAME", "Gemfile*", "HISTORY.*", "node_modules", "package.json", "README.*", ".git", ".idea"]
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
