# Site settings

title: "MandelBig"
email: Jeff@pcjs.org
description: >
  Welcome to MandelBig!
baseurl: ""
url: "http://mandelbig.com"
twitter_username: jeffpar
github_username:  jeffpar
google_analytics: UA-49658648-2

theme: jekyll-theme-cayman
