# Site settings

title: "Mandelbot"
email: Jeff@pcjs.org
description: >
  Welcome to Mandelbot!
baseurl: ""
url: "http://mandelbot.net"
twitter_username: mandelbotnet
github_username:  jeffpar
google_analytics: UA-49658648-2

# Build settings

theme: jekyll-theme-cayman
exclude: ["CNAME", "Gemfile*", "node_modules", "package.json", "README.*", ".git", ".idea"]
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
